http://benalexkeen.com/feature-scaling-with-scikit-learn/
http://www.enlistq.com/feature-scaling-python-using-scikit-learn/
https://t4tutorials.com/min-max-normalization-of-data-in-data-mining/
http://sebastianraschka.com/Articles/2014_about_feature_scaling.html

Scaled data has Zero mean and unit variance 

Standard deviation  = square root of the variance

In [16]:
import numpy as np
from sklearn.preprocessing import scale 
X_train = np.array([[ 1, 2,  3],[ 4,  5,  6],[ 7,  8, 9]])
print('-------------------------------')
print(X_train.size)
print('-------------------------------')
print(X_train.shape)
X_scale = scale(X_train)
print('-------------------------------')
print(X_scale)
print('-------------------------------')
print(X_scale.mean(axis=0))
print('-------------------------------')
print(X_scale.std(axis=0))

-------------------------------
9
-------------------------------
(3, 3)
-------------------------------
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
-------------------------------
[0. 0. 0.]
-------------------------------
[1. 1. 1.]


C:\Users\dasarred\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


minmax_scale is used to scale the feature to a range often between zero and one  

minmax_scale = (v-min)/(max - min)

for 4*1 element the minmax_scale = (20-8)/(20-8) = 1

for 3*1 element the minmax_scale = (15-8)/(20-8) = 7/12 = 0.5833

In [24]:
#Applying minmax scaling on numpy array having one column , if its 3 column then give as ---> minmax_scale(x,columns=[0, 1, 2])
X = np.array([[8], [10], [15],[20]])
print(X.shape)
print('-------------------------------')
print(X)
print('-------------------------------')
from sklearn.preprocessing import minmax_scale
X_minmax_scale = minmax_scale(X)
print(X_minmax_scale)

(4, 1)
-------------------------------
[[ 8]
 [10]
 [15]
 [20]]
-------------------------------
[[0.        ]
 [0.16666667]
 [0.58333333]
 [1.        ]]


C:\Users\dasarred\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64.
  warnings.warn(msg, DataConversionWarning)


In [35]:
#Applying minmax scaling on pandas dataframe
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=(range(6)))
s2 = pd.Series([10, 9, 8, 7, 6, 5], index=(range(6)))
df = pd.DataFrame(s1, columns=['s1'])
df['s2'] = s2
print(df)
print('-------------------------------')
print(minmax_scale(df['s1']))
print('-------------------------------')
print(minmax_scale(df))


   s1  s2
0   1  10
1   2   9
2   3   8
3   4   7
4   5   6
5   6   5
-------------------------------
[0.  0.2 0.4 0.6 0.8 1. ]
-------------------------------
[[0.  1. ]
 [0.2 0.8]
 [0.4 0.6]
 [0.6 0.4]
 [0.8 0.2]
 [1.  0. ]]


C:\Users\dasarred\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)


maxabs_scale is used to scale the feature to a range often between -1 and +1

In [49]:
from sklearn.preprocessing import maxabs_scale
X = np.array([[ 1, -2,  3],[ 4,  5,  6],[ -7,  8, -9]])
X_maxabs_scale = maxabs_scale(X)
print(X)
print('-------------------------------')
print(X_maxabs_scale)

[[ 1 -2  3]
 [ 4  5  6]
 [-7  8 -9]]
-------------------------------
[[ 0.14285714 -0.25        0.33333333]
 [ 0.57142857  0.625       0.66666667]
 [-1.          1.         -1.        ]]
