Parts of Speech  

In [2]:
from nltk import pos_tag
from nltk import word_tokenize
text_data = "Bharath and reddy are close friends"
text_tagged = pos_tag(word_tokenize(text_data))
text_tagged 

[('Bharath', 'NNP'),
 ('and', 'CC'),
 ('reddy', 'NN'),
 ('are', 'VBP'),
 ('close', 'JJ'),
 ('friends', 'NNS')]

Tokenize text 

In [4]:
from nltk.tokenize import word_tokenize, sent_tokenize
string = "The science of today is the technology of tomorrow. Future starts today not tommorrow."
print(word_tokenize(string))
print(sent_tokenize(string))

['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow', '.', 'Future', 'starts', 'today', 'not', 'tommorrow', '.']
['The science of today is the technology of tomorrow.', 'Future starts today not tommorrow.']


Bag of words

In [8]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
text_data = np.array(['bharath like sweets',
                      'Sugar is best',
                      'Ginger is good'])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

print(bag_of_words.toarray())

feature_names = count.get_feature_names()


print(feature_names)

pd.DataFrame(bag_of_words.toarray(), columns=feature_names)



[[0 1 0 0 0 1 0 1]
 [1 0 0 0 1 0 1 0]
 [0 0 1 1 1 0 0 0]]
['best', 'bharath', 'ginger', 'good', 'is', 'like', 'sugar', 'sweets']


best  bharath  ginger  good  is  like  sugar  sweets
0     0        1       0     0   0     1      0       1
1     1        0       0     0   1     0      1       0
2     0        0       1     1   1     0      0       0